### ISSUE TITLE
Documentation: "Add to your project"

### ISSUE THREAD

**Issue by Angus71** [kanflo/esp-open-rtos-driver-i2c#1]
Hi Johan,

I had problems, when I was following your approach regarding the usage as a git submodule

```
% git submodule add https://github.com/kanflo/esp-open-rtos-driver-i2c.git
% mv esp-open-rtos-driver-i2c i2c
```

My proposal would be to use the following in the documentation

```
% git submodule add https://github.com/kanflo/esp-open-rtos-driver-i2c.git i2c
```

So git is able to follow the changed repository name.

Thanks for the great work

 Angus71

**Comment by kanflo** [comment]
Thanks, twice fold! I have updated the docs.
