### ISSUE TITLE
Not working when using gpios unequal to GPIO0/GPIO2?

### ISSUE THREAD

**Issue by Angus71** [kanflo/esp-open-rtos-driver-i2c#2]
Hi Johan,

I used your I2C driver with a ESP-12 module (nodemcu V2) and no communication was possible to the I2C slave, when using GPIO14 as SCL_PIN. I checked for "pull-up" resistors on GPIO14, but even with a "pull-up" it was not working. 

Previously I used a rewritten version of the diver from zarya [1] to work with esp-open-rtos and the GPIO14 was usable right out of the box. 

Are you able to reproduce this?

Thanks for the good work

  Angus71

[1] https://github.com/zarya/esp8266_i2c_driver

**Comment by kanflo** [comment]
Hi Angus,

Thank you and thanks for reporting this! I have not tried GPIO14 but will give it a go.

Regards,
Johan

**Comment by Angus71** [comment]
Hi Johan,

While merging the i2c driver into http://github.com/Angus71/esp-open-rtos I stumbled over a strange thing. I cloned the repo and your fix kanflo@1322268140d9cab673317afb21bff9f3a50efe43 was missing in the cloned repo.

If open the i2c.c file this fix is also missing in the web interface.

I know that this might be a separate issue, but I didn't want to pollute the issue tracker with my inability to work with git :-)

Regards,
Frank

**Comment by kanflo** [comment]
Hi Frank,

That was very very weird. How Github could have a record of the change even though it was missing from the list of commits I cannot explain. It's there now however. Thanks for the heads up!

Cheers,
Johan

I had the change in another cloned repo on my computer but had not pushed it and as you saw the commit was not visible in the history. How
